apiVersion: v1
kind: Secret
metadata:
  name: fiapx-secrets
  namespace: fiapx
type: Opaque
stringData:
  # Altere estes valores!
  SQL_CONNECTION_STRING: "Server=tcp:fiapx-sqlserver-xxxx.database.windows.net,1433;Initial Catalog=FiapXDb;User ID=fiapxadmin;Password=FiapX@2024Secure!;Encrypt=True;TrustServerCertificate=False;"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  JWT_KEY: "FiapX_Super_Secret_Key_2024_Must_Be_At_Least_32_Characters!"
  STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=fiapxstoragexxxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
